version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"